name: Tests

on:
  push:
    branches:
      - 'main'
      - '*.x'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        os: [ubuntu-latest]
        composer-mode: [update]
        symfony-version: ['']
        include:
          # Build on the lowest supported PHP with the lowest supported dependencies
          - php: '8.2'
            os: ubuntu-latest
            composer-mode: lowest
            symfony-version: ''

          # Symfony LTS job:
          - php: '8.2'
            os: ubuntu-latest
            composer-mode: update
            symfony-version: '6.4'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-file: "development"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install latest dependencies
        if: matrix.composer-mode == 'update'
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}.*
        run: composer update

      - name: Install lowest dependencies
        if: matrix.composer-mode == 'lowest'
        run: composer update --prefer-lowest

      - name: Run tests (Behat)
        run: ./vendor/bin/behat --no-colors

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.5']
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Run PHPStan
        run: ./vendor/bin/phpstan

  coding-standard:
    name: Coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Run PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --verbose --diff

  rector:
    name: Rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Run Rector
        run: ./vendor/bin/rector --dry-run
